### ISSUE TITLE
Help question

### ISSUE THREAD

**Issue by Foxwells** [Stadler76/Corruption-of-Champions-Mod#3]
Heyo, sorry for bopping in like this 0: GitHub has no PM feature and I wanted your help with something, so this was kind of the next best thing...

Anyway.

I'm trying to make an NPC which basically would change its appearance upon being hit and taking damage, but only the first time. I fear doing `monster.HP < monster.eMaxHP()` alone would have the appearance change text trigger for every scene, and I'm not quite sure what the `FirstAttack` status does. Tried studying and testing, didn't understand it. Either way it does Not seem tied to the first attack made on the opponent.

You won't be able to Lust attack the enemy so that's not really an issue... Just, first time you land a successful hit that drops HP z_z You have any ideas for what kind of `if` scenario I should set up?

**Comment by Stadler76** [comment]
I assume you're adding a class for that monster, so just add a `Boolean` prop for that to your new class, that is being set to true, when the monster TFs
